services:
  - type: web
    name: gsac
    env: python
    plan: free
    region: oregon
    buildCommand: bash build.sh
    startCommand: gunicorn core.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.prod
      - key: SECRET_KEY
        value: <set-in-dashboard>
      - key: DATABASE_URL
        value: <set-in-dashboard>
      - key: ALLOWED_HOSTS
        value: your-render-app.onrender.com
