services:
  - type: web
    name: c-regist
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.prod
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: c-regist-db
          property: connectionString
    staticPublishPath: staticfiles

databases:
  - name: c-regist-db
    plan: free
